#!/bin/sh
##
## NAME: mega-download
## 
## Made by Stefano Viola
## 
## NOTE: "mega-download" e` un downloader di file hostati 
##       su megaupload.com. Per funzionare bisogna avere 
##       un account premium.
##
## LICENSE: GPL v.3
##
##


AUTHOR="Stefano Viola (aka) Esteban Sannin"
EMAIL="stefanoviola[at]sannioglug[dot]org"
COPYRIGHT="(C) 2010 Stefano Viola"
DATA_BUILD="MAY 2010"
VERSION="0.8"
LICENSE="GPLv3"

CONFIG_FILE_NAME=mega-download.cfg
CONFIG_FILE=`pwd`/$CONFIG_FILE_NAME
LIMIT_RATE_VALUE=`cat $CONFIG_FILE | grep LIMIT | cut -f 2 -d=`              # Valore contenuto nel file di configurazione
DIR_DOWNLOAD_VALUE=`cat $CONFIG_FILE | grep DIR_DOWNLOAD | cut -f 2 -d\"`     # Valore contenuto nel file di configurazione

#sed -i "s%`cat mega-download.cfg | grep LIMIT | cut -f 2 -d=`%1000%g" mega-download.cfg


DIR_DOWNLOAD=`pwd`
LIMIT_RATE=0
FINAL_LINK=`pwd`/.directLink
CONFIG_FILE=`pwd`/mega-download.cfg


read_config()
{ if [ -e $CONFIG_FILE ]; then
        . ./mega-download.cfg
        echo -n "\n\n\tLoaded configuration file mega-download.cfg...\n\n"
        echo -n "   LIMIT_RATE_VALUE =   $LIMIT_RATE_VALUE\n"
        echo -n "   DIR_DOWNLOAD_VALUE = $DIR_DOWNLOAD_VALUE\n\n\n\n"
else
        echo -n "\n\n\tConfiguration file mega-download.cfg not present!\n\n"
        echo "Loaded Default Value:"
        echo "LIMIT_RATE = $LIMIT_RATE (0 is unlimited)"
        echo "DIR_DOWNLOAD = $DIR_DOWNLOAD"
        echo ""
fi
}


version(){
        echo -n "\n\n\tMega-Download v0.5\n\n"
        echo -n "   [INFO]:         Downloader for only Megaupload Premium Users\n\n"
        echo -n "   [AUTHOR]:       $AUTHOR\n"
        echo -n "   [EMAIL]:        $EMAIL\n"
        echo -n "   [COPYRIGHT]:    $COPYRIGHT\n"
        echo -n "   [DATA BUILD]:   $DATA_BUILD\n"
        echo -n "   [VERSION]:      $VERSION\n"
        echo -n "   [LICENSE]:      $LICENSE\n\n\n"

}

clear(){
    rm index.* .directLink .temp
}

usage(){
        echo -n "\n\n"
        echo -n "\tMega-Download the command line downloader\n"
        echo -n "\t(C) 2010 Stefano Viola\n"
        echo -n "\tstefanoviola[at]sannioglug[dot]org\n\n"
        echo "[INFO]:                                                                                                  "
        echo "         Downloader only for Premium Users                                                               "
        echo "[USAGE]:                                                                                                 "
        echo "         mega-download http://link.megaupload.com                                                        "
        echo "         If the cookie does not exist will be asked to create                                            "
        echo "[OPTION]:                                                                                                "
        echo "         -h         Print this help                                                                      "
        echo "         -v         Print version info                                                                   "
        echo "         --list     List mode. Download from a list of link                                              "  
        echo "                    Example: mega-download --list list-link                                              "
        echo "                    list-link= is the file containing the list of links                                  "
        echo "         --config   start the interactive configuration parameters                                       "
        echo ""
        echo "[CONFIGURATION]:    To set up mega-download is easy. There are two possibilities:                        "
        echo "                  1. start \"mega-download --config\" and sets your parameters                           "
        echo ""
        echo "                  2. Create the file:                                                                    "
        echo "                           \"mega-download.cfg\" in the same directory and insert this string:           "
        echo ""
        echo "                    DIR_DOWNLOAD=your-path ---> your-path is the directory where the files are downloaded"
        echo "                    LIMIT_RATE=1000        ---> 1000 is a byte limit to download (0 is unlimited)        "
        echo -n "\n\n"
        #echo -n ""
        #echo -n ""
        #echo -n ""
}
capture_link(){

        ls | grep index > .temp
        number_link=`wc -l .temp | awk {'print $1'}`
        dir="`pwd`/.temp"
        for i in `seq 1 $number_link`;
        do      
                p=p
                sum=$i$p
                temp_link=`sed -n $sum $dir`
                cat_link=`cat $temp_link | grep files`
                cat $temp_link | grep files | cut -f 2 -d\">>.directLink
        done    
}

download_from_list(){
        echo pippo
}


case "$1" in
        -h) usage
                ;;
        -v) version
                ;;
        -t) read_config # for debug.. 
                ;;
  --config) echo $LIMIT_RATE_VALUE
            echo $DIR_DOWNLOAD_VALUE
            control=1
            if [ -e $CONFIG_FILE ]; then
                    while [ $control = 1  ]; do
                    echo -n "\n\t\tSetting your configuration file:\n\n"
                    echo " 1 - Print current value"
                    echo " 2 - Setting current value"
                    echo " 3 - Exit menu config"
                    echo ""
                    echo -n "enter your choice: "
                    read menu_value
                    case "$menu_value" in

                            1) 
                                    echo -n "\nCurrent value:\n\n"
                                    cat $CONFIG_FILE | grep =
                                    echo
                                    ;;
                            2)
                                    echo -n "\nChoose the value to be set:\n\n"
                                    echo " 1 - Setting the Limit Rate"
                                    echo " 2 - Setting the download directory"
                                    echo " 3 - Return to main menu"
                                    echo ""
                                    echo -n "enter your choice: "
                                    read submenu_value
                                    
                                    case "$submenu_value" in
                                            
                                            1)
                                                    echo "Current limit rate is $LIMIT_RATE_VALUE (byte)"
                                                    echo -n "Insert new value (byte): "
                                                    read new_limit_rate
                                                    sed -i "s%$LIMIT_RATE_VALUE%$new_limit_rate%g" $CONFIG_FILE 
                                                    ;;
                                            2)
                                                    echo "Current Download directory is: $DIR_DOWNLOAD_VALUE"
                                                    echo -n "Insert new path: "
                                                    read new_dir_download
                                                    sed -i "s%$DIR_DOWNLOAD_VALUE%$new_dir_download%g" $CONFIG_FILE
                                                    ;;
                                            3)
                                                    echo "Return to main menu"
                                                    ;;
                                            *)
                                                    echo "Immesso valore errato"
                                                    ;;
                                    esac
                                    ;;
                            3)
                                    control=0
                                    echo -n "\nexit\n"
                                    ;;
                            *)
                                    echo "error value"
                                    ;;
                    esac
            done
    else
            echo -n "\n\tConfigure file not present!\t\t\n"
            echo "Creating new file configuration..."
            echo ""
            echo -n "Insert Limit Rate (byte): "
            read limit
            echo -n "Insert Download directory: "
            read directory
            echo "LIMIT_RATE=$limit" >> $CONFIG_FILE_NAME
            echo "DIR_DOWNLOAD=$directory" >> $CONFIG_FILE_NAME
            if [ -e $CONFIG_FILE_NAME  ]; then
                    echo "Configuration file created!"
            else
                    echo "Error file not created"
            fi


    fi
                 
                ;;
    --list)
            echo "LIST MODE"
            wget -c --load-cookies ./cookie -i $2
            capture_link
            echo -n "Download file...\n"
           read_config 
            wget -c --load-cookies ./cookie -i "$FINAL_LINK" --limit-rate=$LIMIT_RATE -P $DIR_DOWNLOAD
            clear

            ;;
         *)
                 if [ -e `pwd`/cookie ]; then
                        if [ -z $1 ]; then               #controllo se ci sono argomenti passati da linea di comando
                                 
                                 echo -n "Insert direct link:\n"
                                 read full_link
                                 echo -n "Get direct link... \n"
                                 sleep 3
                                 wget -c --load-cookies ./cookie  $full_link -q
                                 echo -n "direct link obtained!\n"
                                 capture_link 
                                 echo -n "Download file...\n" 
                                 def_link=`pwd`/.directLink
                                 read_config
                                 wget -c --load-cookies ./cookie -i "$def_link" --limit-rate=$LIMIT_RATE -P $DIR_DOWNLOAD 
                                 clear
                         else 
                                 echo -n "Get direct link... \n"
                                 wget -c --load-cookies ./cookie $1 -q
                                 capture_link
                                 echo -n "Download file...\n" 
                                 read_config
                                 wget -c  --load-cookies ./cookie -i "$FINAL_LINK" --limit-rate=$LIMIT_RATE -P $DIR_DOWNLOAD
                                 clear
                         fi
                 else
                         echo -n "\n\n\tCookie Not present!\n"
                         echo -n "\tGenerating new Cookie...\n\n"
                         echo -n "Insert Megaupload User:\n"
                         read user
                         stty -echo    # Disabilita la visualizzazione sullo schermo.
                         echo -n "Insert Megaupload Password:\n"
                         read passwd
                         stty echo     # Ripristina la visualizzazione sullo schermo.
                         echo -n "Generating the cookie..."
                         wget --save-cookies ./cookie --post-data "login=1&next=c%3Daccount&username=$user&password=$passwd" -O - http://www.megaupload.com/?c=account > /dev/null
                         status=`cat cookie | grep TRUE | awk '{print $2}'`
                         if [ -z $status ]; then
                                 echo -n "Error: Access Failed!\n"
                                 echo -n "Cookie not Generated!\n\n"
                                 rm cookie
                         else
                                 echo -n "Cookie Generated!\n\n"
                         fi
                 fi
                 ;;
 esac
 exit 0

